# Generated by Django 4.2.7 on 2023-11-07 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grocery",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("content", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=100, null=True)),
                ("location", models.CharField(max_length=100)),
                ("price", models.IntegerField(default=0)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="post_img")),
                ("buy_time", models.CharField(max_length=100, null=True)),
                ("recruitment_num", models.IntegerField(null=True)),
                ("post_type", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroceryComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateField(auto_now_add=True)),
                ("content", models.TextField(max_length=100)),
                (
                    "post",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.grocery",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="글제목")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="구매 날짜와 시각"),
                ),
                ("location", models.CharField(max_length=100, verbose_name="위치")),
                ("minimumPrice", models.IntegerField(default=0, verbose_name="최소주문금액")),
                ("link", models.CharField(max_length=100, verbose_name="배달지점링크")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="post-image",
                        verbose_name="작성이미지",
                    ),
                ),
                ("content", models.CharField(max_length=100, verbose_name="내용")),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
