# Generated by Django 4.2.7 on 2023-11-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='latitude',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='longitude',
            field=models.FloatField(max_length=100),
        ),
    ]
