# Generated by Django 4.2.7 on 2023-11-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delivery",
            name="minimumPrice",
            field=models.IntegerField(verbose_name="최소주문금액"),
        ),
    ]
