# Generated by Django 4.2.7 on 2023-11-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_homeDeliveryComment"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
