# Generated by Django 4.2.7 on 2023-11-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_delivery_latitude_alter_delivery_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.AlterField(
            model_name='grocery',
            name='latitude',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='longitude',
            field=models.FloatField(max_length=100),
        ),
    ]
